#SPDX-License-Identifier: MIT-0
---
- name: Nginx | Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Nginx | Copy nginx site configuration
  template:
    src: "{{ nginx_site_template }}"
    dest: "{{ nginx_site_available }}"
  notify: Restart nginx

- name: Nginx | Enable nginx site
  file:
    src: "{{ nginx_site_available }}"
    dest: "{{ nginx_site_enabled }}"
    state: link

- name: Nginx | Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true

